FROM registry.gitlab.com/xoe/odoo/odoo-docker-base

# python and odoo linting setup
RUN pip install --upgrade --pre pylint-odoo
RUN pip install pylint-mccabe coverage

# Some git tools for standard diffing
RUN apt-get update && apt-get install -y --no-install-recommends git-core

ENTRYPOINT []
CMD []
