
# Add odoo-migrate code transformation library
RUN pip --quiet --quiet install --no-cache-dir odoo-migrate; \
    find /usr/local -depth \
        \( \
            \( -type d -a \( -name test -o -name tests \) \) \
            -o \
            \( -type f -a \( -name '*.pyc' -o -name '*.pyo' \) \) \
        \) -exec rm -rf '{}' +;