

USER root

# Some helpeful tools
# Size: ca. 57MB
RUN apt-get -qq update && apt-get -qq install -y curl wget mtr net-tools gnupg

# Local browser testing
# Size: ca. 291MB
RUN wget --quiet -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list \
    && apt-get -qq update && apt-get -qq install -y --no-install-recommends google-chrome-stable > /dev/null

# Environement
ENV WDB_NO_BROWSER_AUTO_OPEN=True \
    WDB_SOCKET_SERVER=wdb \
    WDB_WEB_PORT=1984 \
    WDB_WEB_SERVER=localhost \
    PYTHONPATH=${PYTHONPATH}:${ODOO_FRM} \
    ODOO_TEMPLATES_DIR="/templates" \
    DODOO_LOAD_OUT=/var/lib/dodoo-loader/logs.json

# Python packages
# Size: ca. 138MB
RUN set -ex; \
    \
    savedAptMark="$(apt-mark showmanual)"; \
    apt-get update; \
    apt-get install -y --no-install-recommends build-essential automake libtool; \
    \
        pip --quiet --quiet install --no-cache-dir \
            # Get dodoo-* devops toolchain
            # dodoo-scaffolder \
            # dodoo-translator \
            dodoo-tester \
            dodoo-initializer \
            dodoo-loader \
            dodoo-migrator \
            # Custom Odoo Scaffolding dependency
            pick \
            # General develpoment libraries
            astor \
            pylint-odoo \
            pylint-mccabe \
            coverage \
            ptpython \
            pudb \
            pyinotify \
            watchdog \
            wdb \
            jq \
            # Browser testing, js test recording
            websocket-client \
            ffmpeg; \
        find /usr/local -depth \
            \( \
                \( -type d -a \( -name test -o -name tests \) \) \
                -o \
                \( -type f -a \( -name '*.pyc' -o -name '*.pyo' \) \) \
            \) -exec rm -rf '{}' +; \
    \
    apt-mark auto '.*' > /dev/null; \
    [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark; \
    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
    rm -rf /var/lib/apt/lists/*;

COPY entrypoint.d/* /entrypoint.d/
COPY templates /templates

RUN /bin/bash -c 'shopt -s dotglob \
 && chmod +x /entrypoint.d/* \
 && shopt -u dotglob'

# Prepare odoo owned testlog folder for chrome screenshots
# Prepare odoo owned loading log folder for dodoo loader
RUN mkdir -p /var/lib/odoo-testlogs; \
    chown odoo:odoo /var/lib/odoo-testlogs; \
    mkdir -p /var/lib/dodoo-loader; \
    chown odoo:odoo /var/lib/dodoo-loader
