
# Add odoo-migrate code transformation library
RUN pip --quiet --quiet install --no-cache-dir odoo-module-migrator; \
    find /usr/local -depth \
        \( \
            \( -type d -a \( -name test -o -name tests \) \) \
            -o \
            \( -type f -a \( -name '*.pyc' -o -name '*.pyo' \) \) \
        \) -exec rm -rf '{}' +;

# Phantom for older odoo version
# Size: ca. 68MB
RUN export DOWNLOAD_DIR="$(mktemp -d)" && \
    cd ${DOWNLOAD_DIR} && \
    wget -P ${DOWNLOAD_DIR} -q https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 && \
    tar xf ${DOWNLOAD_DIR}/phantomjs-2.1.1-linux-x86_64.tar.bz2 && \
    cp ${DOWNLOAD_DIR}/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/bin/phantomjs && \
    chmod +x /usr/bin/phantomjs && \
    rm -rf ${DOWNLOAD_DIR}
